import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "./providers";
import NavBar from "@/components/nav/NavBar";
import HamburgerMenu from "@/components/modal/HamburgerMenu";
import NotificationListener from "@/components/notification/NotificationListener";

export const metadata: Metadata = {
  title: "EVALIA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <main className="w-screen h-screen bg-neutral-950 text-neutral-100 ">
              <NavBar/>
              <HamburgerMenu/>
              <NotificationListener />
              {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
